### ISSUE TITLE
Cannot compile msstats on mi MacBook

### ISSUE THREAD

**Issue by MrLocuace** [molpopgen/msstats#5]
Dear Kevin,

I am trying to install msstats in my MacBook Pro Yosemite 10.10.5 but I am unable to do it. I don't have a computational background and I don't have any C++ knowledge.

I followed the instructions provided in GitHub: cd into the msstats directory and run ./configure. I get this:

Lucass-MacBook-Pro:msstats-master lucas$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/Users/lucas/Dropbox/puc/Softwares/msstats-master/missing: Unknown `--is-lightweight' option
Try `/Users/lucas/Dropbox/puc/Softwares/msstats-master/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for an ANSI C-conforming const... yes
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for main in -lgslcblas... no
GSL BLAS runtime library not found

Also, when I write "make":

Lucass-MacBook-Pro:msstats-master lucas$ make
make: *** No targets specified and no makefile found.  Stop.

Or "make install" or "sudo make install" I get:

Lucass-MacBook-Pro:msstats-master lucas$ make install
make: Nothing to be done for `install'.

Lucass-MacBook-Pro:msstats-master lucas$ sudo make install
Password:
make: Nothing to be done for `install'.

Do you have any idea of why I am unable to compile msstats?

Thank you very much in advance
Best regards,
Lucas

**Comment by molpopgen** [comment]
Lucas:

This is the same thing that you emailed me earlier.  My response was that you check currently open issues, which contain the answer.  See #4.

**Comment by MrLocuace** [comment]
Dear Kevin,

I am sorry, I misunderstood that. You can erase it if you want

Thank you and best regards,

Lucas

**Comment by molpopgen** [comment]
Technically, your issue differs from #4.  You are missing the GSL, so no Makefile is made. However, this project is deprecated in favor of pylibseq, which is intended to be installed via bioconda.

**Comment by MrLocuace** [comment]
Thank you

**Comment by MrLocuace** [comment]
Dear Kevin,

do you suggest installing the dev or master branch of msstats?.

Thank you and best regards,

Lucas

**Comment by molpopgen** [comment]
I recommend using msprime + pylibseq instead of ms + msstats.   One could write a custom Python script that does something msstats-like using mspms (installed along with msprime).

However, if you want to use msstats, the dev branch is compatible with the latest libsequence release, which is 1.9.2.

**Comment by molpopgen** [comment]
Yes, the warnings are fine.  However, those warnings will soon become errors, and this package will not be updated.  It really is time to move on to more modern tools--they are a LOT faster.
